name = "UX Evaluations"
license = "MIT"
licenselink = "https://github.com/uradotdesign/hugo-ux-evaluations/blob/master/LICENSE"
description = ""
homepage = "http://evaluations.ura.design/"
tags = ["reveal.js", "slideshows", "pdf", "ux", "ux-research", "user-experience"]
features = []
min_version = "0.110.0"

[author]
  name = "Private Maker"
  homepage = "https://github.com/privatemaker"

[original]
  name = "Based on Hugo Reveal"
  homepage = "https://reveal-hugo.dzello.com"
  repo = "https://github.com/dzello/reveal-hugo"
